---
- name: "Check if {{ application_name }} is installed"
  find:
    name: "{{ toolbox_install_dir }}"
    file_type: "file"
    pattern: 'jetbrains-toolbox'
    use_regex: false
    recurse: true
    depth: 2
  register: is_installed

- name: "Check for multiple installations"
  fail:
    msg:
      "Warning: {{ is_installed.matched }} installations found in {{ toolbox_install_dir }}! Please, fix it manually."
  when: is_installed.matched > 1
  ignore_errors: true

- name: "Installation process"
  block:
    - name: "Download {{ application_name }} of version {{ toolbox_version }}"
      get_url:
        url: "{{ download_url }}"
        dest: "{{ temporary_file_name }}"

    - name: "Install to {{ toolbox_install_dir }}"
      unarchive:
        remote_src: true
        src: "{{ temporary_file_name }}"
        dest: "{{ toolbox_install_dir }}"

    - name: "Remove temporary file"
      file:
        name: "{{ temporary_file_name }}"
        state: "absent"

  when: is_installed.matched == 0

- name: Set Inotify Watches Limit
  sysctl: name="fs.inotify.max_user_watches"
          value="{{ inotify_max_user_watches }}"
          state="present"
          reload="yes"
